version: '3.8'

services:

  db:
    image: postgres:14.5
    container_name: "video-db"
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      timeout: 10s
      retries: 20
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"

  api:
    build: .
    container_name: "video-api"
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "password"
      DB_HOST: "db"
      DB_PORT: "5432"
      SSL_MODE: "disable"
      JWT_SECRET: "potato"
      DOMAIN: "papercup.com"
      MIGRATION_SOURCE: "file:///migrations"
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
